CREATE TABLE STUDENTS (
    STUDENT_ID SERIAL PRIMARY KEY,
    NAME TEXT NOT NULL,
    SURNAME TEXT NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    PHONE_NUMBER TEXT NOT NULL,
    PRIMARY_SKILL TEXT NOT NULL,
    CREATED_DATETIME TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_DATETIME TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE SUBJECTS (
    SUBJECT_ID SERIAL PRIMARY KEY,
    SUBJECT_NAME TEXT NOT NULL,
    TUTOR TEXT NOT NULL
);

CREATE TABLE EXAM_RESULTS (
    EXAM_RESULT_ID SERIAL PRIMARY KEY,
    STUDENT_ID INTEGER NOT NULL REFERENCES STUDENTS(STUDENT_ID),
    SUBJECT_ID INTEGER NOT NULL REFERENCES SUBJECTS(SUBJECT_ID),
    MARK INTEGER NOT NULL
);