-- B-TREE INDEX
CREATE INDEX EXAM_RESULTS_STUDENT_ID_BTREE_IDX ON EXAM_RESULTS USING BTREE (STUDENT_ID);
CREATE INDEX EXAM_RESULTS_SUBJECT_ID_BTREE_IDX ON EXAM_RESULTS USING BTREE (SUBJECT_ID);

-- HASH INDEX
CREATE INDEX EXAM_RESULTS_STUDENT_ID_HASH_IDX ON EXAM_RESULTS USING HASH (STUDENT_ID);
CREATE INDEX EXAM_RESULTS_SUBJECT_ID_HASH_IDX ON EXAM_RESULTS USING HASH (SUBJECT_ID);

-- GIN INDEX
CREATE INDEX EXAM_RESULTS_STUDENT_ID_GIN_IDX ON EXAM_RESULTS USING GIN (STUDENT_ID);
CREATE INDEX EXAM_RESULTS_SUBJECT_ID_GIN_IDX ON EXAM_RESULTS USING GIN (SUBJECT_ID);

-- GIST INDEX
CREATE INDEX EXAM_RESULTS_STUDENT_ID_GIST_IDX ON EXAM_RESULTS USING GIST (STUDENT_ID);
CREATE INDEX EXAM_RESULTS_SUBJECT_ID_GIST_IDX ON EXAM_RESULTS USING GIST (SUBJECT_ID);
